# Generated by Django 5.2.8 on 2025-11-25 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_residente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residente',
            options={'verbose_name': 'Residente', 'verbose_name_plural': 'Residentes'},
        ),
        # migrations.RemoveField(  <--- (Ya estaba comentada)
        #     model_name='residente',
        #     name='email',
        # ),
        # ⬇️ COMENTAR ESTAS DOS LÍNEAS ⬇️
        # migrations.RemoveField(
        #     model_name='residente',
        #     name='nombre',
        # ),
        # migrations.RemoveField(
        #     model_name='residente',
        #     name='unidad',
        # ),
        # ⬆️ COMENTAR ESTAS DOS LÍNEAS ⬆️

        # Las siguientes son operaciones ADD/ALTER, que deben ejecutarse:

        migrations.AddField(
            model_name='residente',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='residente',
            name='dni',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='DNI / Pasaporte'),
        ),
        migrations.AddField(
            model_name='residente',
            name='espacios_estacionamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Estacionamiento'),
        ),
        migrations.AddField(
            model_name='residente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='residente',
            name='nombre_completo',
            field=models.CharField(default='John Doe', max_length=255, verbose_name='Nombre Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residente',
            name='tipo_residente',
            field=models.CharField(choices=[('PR', 'Propietario'), ('AR', 'Arrendatario'), ('FA', 'Familiar/Huésped')], default='PR', max_length=2, verbose_name='Tipo de Residente'),
        ),
        migrations.AddField(
            model_name='residente',
            name='unidad_principal',
            field=models.CharField(default='Torre C-501', max_length=100, verbose_name='Unidad Principal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residente',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo'), ('PE', 'Pendiente de Activación')], default='PE', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('residente', 'Residente'), ('guardia', 'Guardia')], default='residente', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]