# Generated by Django 5.2.8 on 2025-11-26 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_residente_email_remove_residente_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
                ('costo_reserva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'db_table': 'cat_areas_comunes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('puesto', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'db_table': 'frontend_empleado',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('rfc_o_taxid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'db_table': 'frontend_proveedor',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('residente', 'Residente'), ('guardia', 'Guardia'), ('empleado', 'Empleado')], default='residente', max_length=10),
        ),
        migrations.AlterModelTable(
            name='residente',
            table='frontend_residente',
        ),
        migrations.CreateModel(
            name='ControlAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=255)),
                ('tipo_visitante', models.CharField(max_length=50)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('identificacion_presentada', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.residente')),
                ('guardia_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.empleado')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'db_table': 'control_accesos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_recibo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('comprobante_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='frontend.empleado')),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='frontend.residente')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='frontend.proveedor')),
            ],
            options={
                'verbose_name': 'Pago / Cobro',
                'db_table': 'gestion_pagos',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario_o_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frecuencia_pago', models.CharField(max_length=20)),
                ('archivo_contrato_url', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.empleado')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.proveedor')),
            ],
            options={
                'db_table': 'gestion_contratos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.areacomun')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.residente')),
            ],
            options={
                'db_table': 'reservas_areas',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('EMERGENCIA', 'Emergencia')], default='MEDIA', max_length=20)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.empleado')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.proveedor')),
            ],
            options={
                'db_table': 'gestion_tareas',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('EMERGENCIA', 'Emergencia')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(default='ABIERTO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.empleado')),
                ('proveedor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.proveedor')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to='frontend.residente')),
            ],
            options={
                'db_table': 'gestion_tickets',
            },
        ),
    ]
