# Generated by Django 5.2.8 on 2025-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_areacomun_empleado_proveedor_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(max_length=250),
        ),
    ]
