# Generated by Django 5.2.8 on 2025-12-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_residente_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlacceso',
            name='tipo_visitante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='residente',
            name='espacios_estacionamiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estacionamiento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo_solicitud',
            field=models.CharField(max_length=100),
        ),
    ]
