# Generated by Django 5.2.8 on 2025-11-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_residente_options_remove_residente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='residente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='residente',
            name='unidad',
        ),
    ]
