# Generated by Django 5.2.8 on 2025-11-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_reunion', models.DateTimeField()),
                ('acta_url', models.FileField(blank=True, max_length=255, null=True, upload_to='actas/')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada')], default='PROGRAMADA', max_length=20)),
            ],
            options={
                'verbose_name': 'Reunión / Asamblea',
                'verbose_name_plural': 'Reuniones',
                'db_table': 'reuniones_asamblea',
            },
        ),
    ]
