# Generated by Django 5.2.8 on 2025-11-29 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_historiallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 números y 1 letra (ej. 12345678A).', regex='^\\d{8}[A-Za-z]$')], verbose_name='DNI / Pasaporte'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo'), ('PE', 'Pendiente')], default='PE', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números y máximo 10 dígitos.', regex='^\\d{1,10}$')], verbose_name='Teléfono'),
        ),
        migrations.AddConstraint(
            model_name='residente',
            constraint=models.UniqueConstraint(fields=('unidad_principal', 'tipo_residente'), name='uniq_unidad_por_tipo'),
        ),
    ]
